server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"   #gateway, refresh, loggers, info, health
  endpoint:
    loggers:
      enabled: true
    gateway:
      enabled: true # default value
    info:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


springdoc:
#  enable-native-support: true
  webjars:
    prefix: /openapi
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    defaultModelsExpandPath: -1
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /employees/v3/api-docs
        name: Employee Service
        primaryName: Employee Service
      - url: /departments/v3/api-docs
        name: Department Service
        primaryName: Department Service