spring:
  application:
    name: config-server
  profiles:
    active: native

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"   #gateway, refresh, loggers, info, health